---
engines:
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: C
  duplication:
    enabled: true
    config:
      languages:
        python:
          count_threshold: 3
ratings:
  paths:
  - "**.py"
exclude_paths:
- dist/
- tests/
- docs/
