# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x05tests\"\xb9\x05\n\x0eMessageOfTypes\x12\x0c\n\x04\x64ubl\x18\x01 \x01(\x01\x12\x0c\n\x04\x66lot\x18\x02 \x01(\x02\x12\x0b\n\x03i32\x18\x03 \x01(\x05\x12\x0b\n\x03i64\x18\x04 \x01(\x03\x12\x0c\n\x04ui32\x18\x05 \x01(\r\x12\x0c\n\x04ui64\x18\x06 \x01(\x04\x12\x0c\n\x04si32\x18\x07 \x01(\x11\x12\x0c\n\x04si64\x18\x08 \x01(\x12\x12\x0b\n\x03\x66\x33\x32\x18\t \x01(\x07\x12\x0b\n\x03\x66\x36\x34\x18\n \x01(\x06\x12\x0c\n\x04sf32\x18\x0b \x01(\x0f\x12\x0c\n\x04sf64\x18\x0c \x01(\x10\x12\x0b\n\x03\x62ol\x18\r \x01(\x08\x12\r\n\x05strng\x18\x0e \x01(\t\x12\x0c\n\x04\x62yts\x18\x0f \x01(\x0c\x12\x30\n\x06nested\x18\x10 \x01(\x0b\x32 .tests.MessageOfTypes.NestedType\x12\'\n\x03\x65nm\x18\x11 \x01(\x0e\x32\x1a.tests.MessageOfTypes.Enum\x12\x38\n\x0enestedRepeated\x18\x12 \x03(\x0b\x32 .tests.MessageOfTypes.NestedType\x12\x14\n\x0cstr_repeated\x18\x13 \x03(\t\x12\x37\n\tsimpleMap\x18\x14 \x03(\x0b\x32$.tests.MessageOfTypes.SimpleMapEntry\x12\x37\n\tnestedMap\x18\x15 \x03(\x0b\x32$.tests.MessageOfTypes.NestedMapEntry\x1a\x30\n\x0eSimpleMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1aR\n\x0eNestedMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .tests.MessageOfTypes.NestedType:\x02\x38\x01\x1a\x19\n\nNestedType\x12\x0b\n\x03req\x18\x01 \x01(\t\"\x1b\n\x04\x45num\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x12\x05\n\x01\x43\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEOFTYPES_SIMPLEMAPENTRY']._loaded_options = None
  _globals['_MESSAGEOFTYPES_SIMPLEMAPENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGEOFTYPES_NESTEDMAPENTRY']._loaded_options = None
  _globals['_MESSAGEOFTYPES_NESTEDMAPENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGEOFTYPES']._serialized_start=24
  _globals['_MESSAGEOFTYPES']._serialized_end=721
  _globals['_MESSAGEOFTYPES_SIMPLEMAPENTRY']._serialized_start=533
  _globals['_MESSAGEOFTYPES_SIMPLEMAPENTRY']._serialized_end=581
  _globals['_MESSAGEOFTYPES_NESTEDMAPENTRY']._serialized_start=583
  _globals['_MESSAGEOFTYPES_NESTEDMAPENTRY']._serialized_end=665
  _globals['_MESSAGEOFTYPES_NESTEDTYPE']._serialized_start=667
  _globals['_MESSAGEOFTYPES_NESTEDTYPE']._serialized_end=692
  _globals['_MESSAGEOFTYPES_ENUM']._serialized_start=694
  _globals['_MESSAGEOFTYPES_ENUM']._serialized_end=721
# @@protoc_insertion_point(module_scope)
