# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: default.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='default.proto',
  package='sea',
  syntax='proto3',
  serialized_pb=_b('\n\rdefault.proto\x12\x03sea\"\n\n\x08\x45mptyResB#\n\x0f\x63om.shanbay.seaB\x08SeaProtoP\x01\xa2\x02\x03SEAb\x06proto3')
)




_EMPTYRES = _descriptor.Descriptor(
  name='EmptyRes',
  full_name='sea.EmptyRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=32,
)

DESCRIPTOR.message_types_by_name['EmptyRes'] = _EMPTYRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRes = _reflection.GeneratedProtocolMessageType('EmptyRes', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYRES,
  __module__ = 'default_pb2'
  # @@protoc_insertion_point(class_scope:sea.EmptyRes)
  ))
_sym_db.RegisterMessage(EmptyRes)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017com.shanbay.seaB\010SeaProtoP\001\242\002\003SEA'))
# @@protoc_insertion_point(module_scope)
